# File name: floatlayout.kv
#:kivy 1.9.0
<Button>:
    color: .8,.9,0,1
    font_size: 32
    size_hint: .4, .3

<FloatLayout>:
    Button:
        text: 'NO'
        pos_hint: {'x': 0, 'top': 1}
    Button:
        text: 'NE'
        pos_hint: {'right': 1, 'top': 1}
    Button:
        text: 'SE'
        pos_hint: {'y': 0, 'right': 1}
    Button:
        text: 'SO'
        pos_hint: {'x': 0, 'y': 0}
    Button:
        text: 'Centro'
        pos_hint: {'center_x': .5, 'center_y': .5}
